//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj_PB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMSAdmin
    {
        public int Id { get; set; }
        public string nazwaUzytkownika { get; set; }
        public string haslo { get; set; }
    }
}
